name: practice-workflow

on:
    push: 
        branches: 
            main
        branches-ignore: 
            pavan

            
    workflow_dispatch: 

env:
    my_name: pavan

jobs:
    job1:
        runs-on: ubuntu-22.04

        steps:
            - name: step1
              run: echo "hi im ${{env.my_name}}"

            - name: step2
              run: mvn install  